<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Miko-Lap-148" failures="16" tests="22" name="authentication.Register" time="19.674" errors="6" timestamp="2022-10-09T19:56:46 IST" skipped="0">
  <testcase classname="authentication.Register" name="mIKO_AUTH_033_RegisterTests" time="0.878">
    <failure message="The following asserts failed:
	Response showing different status code. expected [200] but found [422],
	Response showing different status message. expected [true] but found [false],
	Response showing different mobile no expected [+919555555555] but found [null],
	Response showing different message expected [Otp sent successfully] but found [null],
	Response showing different status code. expected [200] but found [422],
	Response showing different status message. expected [true] but found [false],
	Response showing different email address expected [user05@testing.com] but found [null],
	Response showing different message expected [Otp sent successfully] but found [null],
	Response showing different status code. expected [200] but found [422],
	Response showing different status message. expected [true] but found [false],
	Response showing different phone no . expected [+919555555555] but found [null],
	Response showing different email address expected [user05@testing.com] but found [null],
	Response showing different message expected [Otp sent successfully] but found [null],
	Response showing different status code. expected [200] but found [422],
	Response showing different status message. expected [true] but found [false],
	Response showing different phone no . expected [+919555555555] but found [null],
	Response showing different email address expected [user05@testing.com] but found [null],
	Response showing First name expected [Test] but found [null],
	Response showing different Last name expected [Ing] but found [null],
	Response showing different message expected [Otp sent successfully] but found [null],
	Response showing different message expected [email_phone_of_diff_user] but found [null],
	Response showing different message expected [email_phone_of_diff_user] but found [null]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Response showing different status code. expected [200] but found [422],
Response showing different status message. expected [true] but found [false],
Response showing different mobile no expected [+919555555555] but found [null],
Response showing different message expected [Otp sent successfully] but found [null],
Response showing different status code. expected [200] but found [422],
Response showing different status message. expected [true] but found [false],
Response showing different email address expected [user05@testing.com] but found [null],
Response showing different message expected [Otp sent successfully] but found [null],
Response showing different status code. expected [200] but found [422],
Response showing different status message. expected [true] but found [false],
Response showing different phone no . expected [+919555555555] but found [null],
Response showing different email address expected [user05@testing.com] but found [null],
Response showing different message expected [Otp sent successfully] but found [null],
Response showing different status code. expected [200] but found [422],
Response showing different status message. expected [true] but found [false],
Response showing different phone no . expected [+919555555555] but found [null],
Response showing different email address expected [user05@testing.com] but found [null],
Response showing First name expected [Test] but found [null],
Response showing different Last name expected [Ing] but found [null],
Response showing different message expected [Otp sent successfully] but found [null],
Response showing different message expected [email_phone_of_diff_user] but found [null],
Response showing different message expected [email_phone_of_diff_user] but found [null]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at authentication.Register.mIKO_AUTH_033_RegisterTests(Register.java:182)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- mIKO_AUTH_033_RegisterTests -->
  <system-out/>
  <testcase classname="authentication.Register" name="mIKO_AUTH_031_RegisterTests" time="0.861">
    <failure message="The following asserts failed:
	Response showing different status code. expected [200] but found [422],
	Response showing different status message. expected [true] but found [false],
	Response showing different mobile no expected [+919555555555] but found [null],
	Response showing different message expected [Otp sent successfully] but found [null],
	Response showing different status code. expected [200] but found [422],
	Response showing different status message. expected [true] but found [false],
	Response showing different email address expected [user05@testing.com] but found [null],
	Response showing different message expected [Otp sent successfully] but found [null],
	Response showing different status code. expected [200] but found [422],
	Response showing different status message. expected [true] but found [false],
	Response showing different phone no . expected [+919555555555] but found [null],
	Response showing different email address expected [user05@testing.com] but found [null],
	Response showing different message expected [Otp sent successfully] but found [null],
	Response showing different status code. expected [200] but found [422],
	Response showing different status message. expected [true] but found [false],
	Response showing different phone no . expected [+919555555555] but found [null],
	Response showing different email address expected [user05@testing.com] but found [null],
	Response showing First name expected [Test] but found [null],
	Response showing different Last name expected [Ing] but found [null],
	Response showing different message expected [Otp sent successfully] but found [null]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Response showing different status code. expected [200] but found [422],
Response showing different status message. expected [true] but found [false],
Response showing different mobile no expected [+919555555555] but found [null],
Response showing different message expected [Otp sent successfully] but found [null],
Response showing different status code. expected [200] but found [422],
Response showing different status message. expected [true] but found [false],
Response showing different email address expected [user05@testing.com] but found [null],
Response showing different message expected [Otp sent successfully] but found [null],
Response showing different status code. expected [200] but found [422],
Response showing different status message. expected [true] but found [false],
Response showing different phone no . expected [+919555555555] but found [null],
Response showing different email address expected [user05@testing.com] but found [null],
Response showing different message expected [Otp sent successfully] but found [null],
Response showing different status code. expected [200] but found [422],
Response showing different status message. expected [true] but found [false],
Response showing different phone no . expected [+919555555555] but found [null],
Response showing different email address expected [user05@testing.com] but found [null],
Response showing First name expected [Test] but found [null],
Response showing different Last name expected [Ing] but found [null],
Response showing different message expected [Otp sent successfully] but found [null]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at authentication.Register.mIKO_AUTH_031_RegisterTests(Register.java:134)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- mIKO_AUTH_031_RegisterTests -->
  <system-out/>
  <testcase classname="authentication.Register" name="mIKO_AUTH_042_RegisterTests" time="0.881">
    <error message="Cannot invoke method getAt() on null object" type="java.lang.IllegalArgumentException">
      <![CDATA[java.lang.IllegalArgumentException: Cannot invoke method getAt() on null object
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:72)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:286)
at io.restassured.internal.path.json.JSONAssertion.getAsJsonObject(JSONAssertion.groovy:57)
at io.restassured.internal.path.json.JSONAssertion$getAsJsonObject.callCurrent(Unknown Source)
at io.restassured.internal.path.json.JSONAssertion.getResult(JSONAssertion.groovy:28)
at io.restassured.path.json.JsonPath.get(JsonPath.java:203)
at com.miko.genericUtils.RestAssuredUtil.getJsonData(RestAssuredUtil.java:20)
at authentication.Register.mIKO_AUTH_042_RegisterTests(Register.java:368)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.NullPointerException: Cannot invoke method getAt() on null object
at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:44)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:34)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
at Script1.run(Script1.groovy:1)
at groovy.lang.GroovyShell.evaluate(GroovyShell.java:431)
at groovy.lang.GroovyShell.evaluate(GroovyShell.java:465)
at groovy.lang.GroovyShell.evaluate(GroovyShell.java:440)
at jdk.internal.reflect.GeneratedMethodAccessor153.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrap.invoke(PogoMetaMethodSite.java:182)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:73)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
at io.restassured.internal.path.json.JSONAssertion.eval(JSONAssertion.groovy:80)
at jdk.internal.reflect.GeneratedMethodAccessor152.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:193)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:61)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:203)
at io.restassured.internal.path.json.JSONAssertion.getAsJsonObject(JSONAssertion.groovy:46)
... 33 more
]]>
    </error>
  </testcase> <!-- mIKO_AUTH_042_RegisterTests -->
  <system-out/>
  <testcase classname="authentication.Register" name="mIKO_AUTH_029_RegisterTests" time="0.875">
    <failure message="The following asserts failed:
	Response showing different status code. expected [200] but found [422],
	Response showing different status message. expected [true] but found [false],
	Response showing different mobile no expected [+919555555555] but found [null],
	Response showing different message expected [Otp sent successfully] but found [null],
	Response showing different status code. expected [200] but found [422],
	Response showing different status message. expected [true] but found [false],
	Response showing different email address expected [user05@testing.com] but found [null],
	Response showing different message expected [Otp sent successfully] but found [null]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Response showing different status code. expected [200] but found [422],
Response showing different status message. expected [true] but found [false],
Response showing different mobile no expected [+919555555555] but found [null],
Response showing different message expected [Otp sent successfully] but found [null],
Response showing different status code. expected [200] but found [422],
Response showing different status message. expected [true] but found [false],
Response showing different email address expected [user05@testing.com] but found [null],
Response showing different message expected [Otp sent successfully] but found [null]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at authentication.Register.mIKO_AUTH_029_RegisterTests(Register.java:77)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- mIKO_AUTH_029_RegisterTests -->
  <system-out/>
  <testcase classname="authentication.Register" name="mIKO_AUTH_035_RegisterTests" time="1.090">
    <failure message="The following asserts failed:
	Response showing different status code. expected [200] but found [422],
	Response showing different status message. expected [true] but found [false],
	Response showing different mobile no expected [+919555555555] but found [null],
	Response showing different message expected [Otp sent successfully] but found [null],
	Response showing different status code. expected [200] but found [422],
	Response showing different status message. expected [true] but found [false],
	Response showing different email address expected [user05@testing.com] but found [null],
	Response showing different message expected [Otp sent successfully] but found [null],
	Response showing different status code. expected [200] but found [422],
	Response showing different status message. expected [true] but found [false],
	Response showing different phone no . expected [+919555555555] but found [null],
	Response showing different email address expected [user05@testing.com] but found [null],
	Response showing different message expected [Otp sent successfully] but found [null],
	Response showing different status code. expected [200] but found [422],
	Response showing different status message. expected [true] but found [false],
	Response showing different phone no . expected [+919555555555] but found [null],
	Response showing different email address expected [user05@testing.com] but found [null],
	Response showing First name expected [Test] but found [null],
	Response showing different Last name expected [Ing] but found [null],
	Response showing different message expected [Otp sent successfully] but found [null],
	Response showing different message expected [email_phone_of_diff_user] but found [null],
	Response showing different message expected [email_phone_of_diff_user] but found [null]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Response showing different status code. expected [200] but found [422],
Response showing different status message. expected [true] but found [false],
Response showing different mobile no expected [+919555555555] but found [null],
Response showing different message expected [Otp sent successfully] but found [null],
Response showing different status code. expected [200] but found [422],
Response showing different status message. expected [true] but found [false],
Response showing different email address expected [user05@testing.com] but found [null],
Response showing different message expected [Otp sent successfully] but found [null],
Response showing different status code. expected [200] but found [422],
Response showing different status message. expected [true] but found [false],
Response showing different phone no . expected [+919555555555] but found [null],
Response showing different email address expected [user05@testing.com] but found [null],
Response showing different message expected [Otp sent successfully] but found [null],
Response showing different status code. expected [200] but found [422],
Response showing different status message. expected [true] but found [false],
Response showing different phone no . expected [+919555555555] but found [null],
Response showing different email address expected [user05@testing.com] but found [null],
Response showing First name expected [Test] but found [null],
Response showing different Last name expected [Ing] but found [null],
Response showing different message expected [Otp sent successfully] but found [null],
Response showing different message expected [email_phone_of_diff_user] but found [null],
Response showing different message expected [email_phone_of_diff_user] but found [null]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at authentication.Register.mIKO_AUTH_035_RegisterTests(Register.java:222)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- mIKO_AUTH_035_RegisterTests -->
  <system-out/>
  <testcase classname="authentication.Register" name="mIKO_AUTH_048_RegisterTests" time="0.838">
    <error message="Cannot invoke method getAt() on null object" type="java.lang.IllegalArgumentException">
      <![CDATA[java.lang.IllegalArgumentException: Cannot invoke method getAt() on null object
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:72)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:286)
at io.restassured.internal.path.json.JSONAssertion.getAsJsonObject(JSONAssertion.groovy:57)
at io.restassured.internal.path.json.JSONAssertion$getAsJsonObject.callCurrent(Unknown Source)
at io.restassured.internal.path.json.JSONAssertion.getResult(JSONAssertion.groovy:28)
at io.restassured.path.json.JsonPath.get(JsonPath.java:203)
at com.miko.genericUtils.RestAssuredUtil.getJsonData(RestAssuredUtil.java:20)
at authentication.Register.mIKO_AUTH_048_RegisterTests(Register.java:501)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.NullPointerException: Cannot invoke method getAt() on null object
at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:44)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:34)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
at Script1.run(Script1.groovy:1)
at groovy.lang.GroovyShell.evaluate(GroovyShell.java:431)
at groovy.lang.GroovyShell.evaluate(GroovyShell.java:465)
at groovy.lang.GroovyShell.evaluate(GroovyShell.java:440)
at jdk.internal.reflect.GeneratedMethodAccessor153.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrap.invoke(PogoMetaMethodSite.java:182)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:73)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
at io.restassured.internal.path.json.JSONAssertion.eval(JSONAssertion.groovy:80)
at jdk.internal.reflect.GeneratedMethodAccessor152.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:193)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:61)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:203)
at io.restassured.internal.path.json.JSONAssertion.getAsJsonObject(JSONAssertion.groovy:46)
... 33 more
]]>
    </error>
  </testcase> <!-- mIKO_AUTH_048_RegisterTests -->
  <system-out/>
  <testcase classname="authentication.Register" name="mIKO_AUTH_030_RegisterTests" time="0.941">
    <failure message="The following asserts failed:
	Response showing different status code. expected [200] but found [422],
	Response showing different status message. expected [true] but found [false],
	Response showing different mobile no expected [+919555555555] but found [null],
	Response showing different message expected [Otp sent successfully] but found [null],
	Response showing different status code. expected [200] but found [422],
	Response showing different status message. expected [true] but found [false],
	Response showing different email address expected [user05@testing.com] but found [null],
	Response showing different message expected [Otp sent successfully] but found [null],
	Response showing different status code. expected [200] but found [422],
	Response showing different status message. expected [true] but found [false],
	Response showing different phone no . expected [+919555555555] but found [null],
	Response showing different email address expected [user05@testing.com] but found [null],
	Response showing different message expected [Otp sent successfully] but found [null]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Response showing different status code. expected [200] but found [422],
Response showing different status message. expected [true] but found [false],
Response showing different mobile no expected [+919555555555] but found [null],
Response showing different message expected [Otp sent successfully] but found [null],
Response showing different status code. expected [200] but found [422],
Response showing different status message. expected [true] but found [false],
Response showing different email address expected [user05@testing.com] but found [null],
Response showing different message expected [Otp sent successfully] but found [null],
Response showing different status code. expected [200] but found [422],
Response showing different status message. expected [true] but found [false],
Response showing different phone no . expected [+919555555555] but found [null],
Response showing different email address expected [user05@testing.com] but found [null],
Response showing different message expected [Otp sent successfully] but found [null]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at authentication.Register.mIKO_AUTH_030_RegisterTests(Register.java:104)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- mIKO_AUTH_030_RegisterTests -->
  <system-out/>
  <testcase classname="authentication.Register" name="mIKO_AUTH_032_RegisterTests" time="0.857">
    <failure message="The following asserts failed:
	Response showing different status code. expected [200] but found [422],
	Response showing different status message. expected [true] but found [false],
	Response showing different mobile no expected [+919555555555] but found [null],
	Response showing different message expected [Otp sent successfully] but found [null],
	Response showing different status code. expected [200] but found [422],
	Response showing different status message. expected [true] but found [false],
	Response showing different email address expected [user05@testing.com] but found [null],
	Response showing different message expected [Otp sent successfully] but found [null],
	Response showing different status code. expected [200] but found [422],
	Response showing different status message. expected [true] but found [false],
	Response showing different phone no . expected [+919555555555] but found [null],
	Response showing different email address expected [user05@testing.com] but found [null],
	Response showing different message expected [Otp sent successfully] but found [null],
	Response showing different status code. expected [200] but found [422],
	Response showing different status message. expected [true] but found [false],
	Response showing different phone no . expected [+919555555555] but found [null],
	Response showing different email address expected [user05@testing.com] but found [null],
	Response showing First name expected [Test] but found [null],
	Response showing different Last name expected [Ing] but found [null],
	Response showing different message expected [Otp sent successfully] but found [null],
	Response showing different message expected [email_phone_of_diff_user] but found [null]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Response showing different status code. expected [200] but found [422],
Response showing different status message. expected [true] but found [false],
Response showing different mobile no expected [+919555555555] but found [null],
Response showing different message expected [Otp sent successfully] but found [null],
Response showing different status code. expected [200] but found [422],
Response showing different status message. expected [true] but found [false],
Response showing different email address expected [user05@testing.com] but found [null],
Response showing different message expected [Otp sent successfully] but found [null],
Response showing different status code. expected [200] but found [422],
Response showing different status message. expected [true] but found [false],
Response showing different phone no . expected [+919555555555] but found [null],
Response showing different email address expected [user05@testing.com] but found [null],
Response showing different message expected [Otp sent successfully] but found [null],
Response showing different status code. expected [200] but found [422],
Response showing different status message. expected [true] but found [false],
Response showing different phone no . expected [+919555555555] but found [null],
Response showing different email address expected [user05@testing.com] but found [null],
Response showing First name expected [Test] but found [null],
Response showing different Last name expected [Ing] but found [null],
Response showing different message expected [Otp sent successfully] but found [null],
Response showing different message expected [email_phone_of_diff_user] but found [null]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at authentication.Register.mIKO_AUTH_032_RegisterTests(Register.java:159)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- mIKO_AUTH_032_RegisterTests -->
  <system-out/>
  <testcase classname="authentication.Register" name="mIKO_AUTH_038_RegisterTests" time="0.825">
    <failure message="The following asserts failed:
	Response showing different status code. expected [200] but found [422],
	Response showing different status message. expected [true] but found [false],
	Response showing different mobile no expected [+919555555555] but found [null],
	Response showing different message expected [Otp sent successfully] but found [null],
	Response showing different status code. expected [200] but found [422],
	Response showing different status message. expected [true] but found [false],
	Response showing different email address expected [user05@testing.com] but found [null],
	Response showing different message expected [Otp sent successfully] but found [null],
	Response showing different status code. expected [200] but found [422],
	Response showing different status message. expected [true] but found [false],
	Response showing different phone no . expected [+919555555555] but found [null],
	Response showing different email address expected [user05@testing.com] but found [null],
	Response showing different message expected [Otp sent successfully] but found [null],
	Response showing different status code. expected [200] but found [422],
	Response showing different status message. expected [true] but found [false],
	Response showing different phone no . expected [+919555555555] but found [null],
	Response showing different email address expected [user05@testing.com] but found [null],
	Response showing First name expected [Test] but found [null],
	Response showing different Last name expected [Ing] but found [null],
	Response showing different message expected [Otp sent successfully] but found [null],
	Response showing different message expected [email_phone_of_diff_user] but found [null],
	Response showing different message expected [email_phone_of_diff_user] but found [null]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Response showing different status code. expected [200] but found [422],
Response showing different status message. expected [true] but found [false],
Response showing different mobile no expected [+919555555555] but found [null],
Response showing different message expected [Otp sent successfully] but found [null],
Response showing different status code. expected [200] but found [422],
Response showing different status message. expected [true] but found [false],
Response showing different email address expected [user05@testing.com] but found [null],
Response showing different message expected [Otp sent successfully] but found [null],
Response showing different status code. expected [200] but found [422],
Response showing different status message. expected [true] but found [false],
Response showing different phone no . expected [+919555555555] but found [null],
Response showing different email address expected [user05@testing.com] but found [null],
Response showing different message expected [Otp sent successfully] but found [null],
Response showing different status code. expected [200] but found [422],
Response showing different status message. expected [true] but found [false],
Response showing different phone no . expected [+919555555555] but found [null],
Response showing different email address expected [user05@testing.com] but found [null],
Response showing First name expected [Test] but found [null],
Response showing different Last name expected [Ing] but found [null],
Response showing different message expected [Otp sent successfully] but found [null],
Response showing different message expected [email_phone_of_diff_user] but found [null],
Response showing different message expected [email_phone_of_diff_user] but found [null]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at authentication.Register.mIKO_AUTH_038_RegisterTests(Register.java:285)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- mIKO_AUTH_038_RegisterTests -->
  <system-out/>
  <testcase classname="authentication.Register" name="mIKO_AUTH_049_RegisterTests" time="0.856">
    <error message="Cannot invoke method getAt() on null object" type="java.lang.IllegalArgumentException">
      <![CDATA[java.lang.IllegalArgumentException: Cannot invoke method getAt() on null object
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:72)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:286)
at io.restassured.internal.path.json.JSONAssertion.getAsJsonObject(JSONAssertion.groovy:57)
at io.restassured.internal.path.json.JSONAssertion$getAsJsonObject.callCurrent(Unknown Source)
at io.restassured.internal.path.json.JSONAssertion.getResult(JSONAssertion.groovy:28)
at io.restassured.path.json.JsonPath.get(JsonPath.java:203)
at com.miko.genericUtils.RestAssuredUtil.getJsonData(RestAssuredUtil.java:20)
at authentication.Register.mIKO_AUTH_049_RegisterTests(Register.java:526)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.NullPointerException: Cannot invoke method getAt() on null object
at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:44)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:34)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
at Script1.run(Script1.groovy:1)
at groovy.lang.GroovyShell.evaluate(GroovyShell.java:431)
at groovy.lang.GroovyShell.evaluate(GroovyShell.java:465)
at groovy.lang.GroovyShell.evaluate(GroovyShell.java:440)
at jdk.internal.reflect.GeneratedMethodAccessor153.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrap.invoke(PogoMetaMethodSite.java:182)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:73)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
at io.restassured.internal.path.json.JSONAssertion.eval(JSONAssertion.groovy:80)
at jdk.internal.reflect.GeneratedMethodAccessor152.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:193)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:61)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:203)
at io.restassured.internal.path.json.JSONAssertion.getAsJsonObject(JSONAssertion.groovy:46)
... 33 more
]]>
    </error>
  </testcase> <!-- mIKO_AUTH_049_RegisterTests -->
  <system-out/>
  <testcase classname="authentication.Register" name="mIKO_AUTH_045_RegisterTests" time="0.921">
    <failure message="The following asserts failed:
	Response showing different status code. expected [200] but found [422],
	Response showing different status message. expected [true] but found [false],
	Response showing different mobile no expected [+919555555555] but found [null],
	Response showing different message expected [Otp sent successfully] but found [null],
	Response showing different status code. expected [200] but found [422],
	Response showing different status message. expected [true] but found [false],
	Response showing different email address expected [user05@testing.com] but found [null],
	Response showing different message expected [Otp sent successfully] but found [null],
	Response showing different status code. expected [200] but found [422],
	Response showing different status message. expected [true] but found [false],
	Response showing different phone no . expected [+919555555555] but found [null],
	Response showing different email address expected [user05@testing.com] but found [null],
	Response showing different message expected [Otp sent successfully] but found [null],
	Response showing different status code. expected [200] but found [422],
	Response showing different status message. expected [true] but found [false],
	Response showing different phone no . expected [+919555555555] but found [null],
	Response showing different email address expected [user05@testing.com] but found [null],
	Response showing First name expected [Test] but found [null],
	Response showing different Last name expected [Ing] but found [null],
	Response showing different message expected [Otp sent successfully] but found [null],
	Response showing different message expected [email_phone_of_diff_user] but found [null],
	Response showing different message expected [email_phone_of_diff_user] but found [null],
	Response showing different status code. expected [200] but found [422],
	Response showing different status message. expected [true] but found [false],
	Response showing different error expected [Otp sent successfully] but found [null],
	Response showing different error expected [user789@testing.com] but found [null]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Response showing different status code. expected [200] but found [422],
Response showing different status message. expected [true] but found [false],
Response showing different mobile no expected [+919555555555] but found [null],
Response showing different message expected [Otp sent successfully] but found [null],
Response showing different status code. expected [200] but found [422],
Response showing different status message. expected [true] but found [false],
Response showing different email address expected [user05@testing.com] but found [null],
Response showing different message expected [Otp sent successfully] but found [null],
Response showing different status code. expected [200] but found [422],
Response showing different status message. expected [true] but found [false],
Response showing different phone no . expected [+919555555555] but found [null],
Response showing different email address expected [user05@testing.com] but found [null],
Response showing different message expected [Otp sent successfully] but found [null],
Response showing different status code. expected [200] but found [422],
Response showing different status message. expected [true] but found [false],
Response showing different phone no . expected [+919555555555] but found [null],
Response showing different email address expected [user05@testing.com] but found [null],
Response showing First name expected [Test] but found [null],
Response showing different Last name expected [Ing] but found [null],
Response showing different message expected [Otp sent successfully] but found [null],
Response showing different message expected [email_phone_of_diff_user] but found [null],
Response showing different message expected [email_phone_of_diff_user] but found [null],
Response showing different status code. expected [200] but found [422],
Response showing different status message. expected [true] but found [false],
Response showing different error expected [Otp sent successfully] but found [null],
Response showing different error expected [user789@testing.com] but found [null]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at authentication.Register.mIKO_AUTH_045_RegisterTests(Register.java:434)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- mIKO_AUTH_045_RegisterTests -->
  <system-out/>
  <testcase classname="authentication.Register" name="mIKO_AUTH_039_RegisterTests" time="0.943">
    <failure message="The following asserts failed:
	Response showing different status code. expected [200] but found [422],
	Response showing different status message. expected [true] but found [false],
	Response showing different mobile no expected [+919555555555] but found [null],
	Response showing different message expected [Otp sent successfully] but found [null],
	Response showing different status code. expected [200] but found [422],
	Response showing different status message. expected [true] but found [false],
	Response showing different email address expected [user05@testing.com] but found [null],
	Response showing different message expected [Otp sent successfully] but found [null],
	Response showing different status code. expected [200] but found [422],
	Response showing different status message. expected [true] but found [false],
	Response showing different phone no . expected [+919555555555] but found [null],
	Response showing different email address expected [user05@testing.com] but found [null],
	Response showing different message expected [Otp sent successfully] but found [null],
	Response showing different status code. expected [200] but found [422],
	Response showing different status message. expected [true] but found [false],
	Response showing different phone no . expected [+919555555555] but found [null],
	Response showing different email address expected [user05@testing.com] but found [null],
	Response showing First name expected [Test] but found [null],
	Response showing different Last name expected [Ing] but found [null],
	Response showing different message expected [Otp sent successfully] but found [null],
	Response showing different message expected [email_phone_of_diff_user] but found [null],
	Response showing different message expected [email_phone_of_diff_user] but found [null]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Response showing different status code. expected [200] but found [422],
Response showing different status message. expected [true] but found [false],
Response showing different mobile no expected [+919555555555] but found [null],
Response showing different message expected [Otp sent successfully] but found [null],
Response showing different status code. expected [200] but found [422],
Response showing different status message. expected [true] but found [false],
Response showing different email address expected [user05@testing.com] but found [null],
Response showing different message expected [Otp sent successfully] but found [null],
Response showing different status code. expected [200] but found [422],
Response showing different status message. expected [true] but found [false],
Response showing different phone no . expected [+919555555555] but found [null],
Response showing different email address expected [user05@testing.com] but found [null],
Response showing different message expected [Otp sent successfully] but found [null],
Response showing different status code. expected [200] but found [422],
Response showing different status message. expected [true] but found [false],
Response showing different phone no . expected [+919555555555] but found [null],
Response showing different email address expected [user05@testing.com] but found [null],
Response showing First name expected [Test] but found [null],
Response showing different Last name expected [Ing] but found [null],
Response showing different message expected [Otp sent successfully] but found [null],
Response showing different message expected [email_phone_of_diff_user] but found [null],
Response showing different message expected [email_phone_of_diff_user] but found [null]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at authentication.Register.mIKO_AUTH_039_RegisterTests(Register.java:306)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- mIKO_AUTH_039_RegisterTests -->
  <system-out/>
  <testcase classname="authentication.Register" name="mIKO_AUTH_041_RegisterTests" time="0.829">
    <error message="Cannot invoke method getAt() on null object" type="java.lang.IllegalArgumentException">
      <![CDATA[java.lang.IllegalArgumentException: Cannot invoke method getAt() on null object
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:72)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:286)
at io.restassured.internal.path.json.JSONAssertion.getAsJsonObject(JSONAssertion.groovy:57)
at io.restassured.internal.path.json.JSONAssertion$getAsJsonObject.callCurrent(Unknown Source)
at io.restassured.internal.path.json.JSONAssertion.getResult(JSONAssertion.groovy:28)
at io.restassured.path.json.JsonPath.get(JsonPath.java:203)
at com.miko.genericUtils.RestAssuredUtil.getJsonData(RestAssuredUtil.java:20)
at authentication.Register.mIKO_AUTH_041_RegisterTests(Register.java:347)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.NullPointerException: Cannot invoke method getAt() on null object
at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:44)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:34)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
at Script1.run(Script1.groovy:1)
at groovy.lang.GroovyShell.evaluate(GroovyShell.java:431)
at groovy.lang.GroovyShell.evaluate(GroovyShell.java:465)
at groovy.lang.GroovyShell.evaluate(GroovyShell.java:440)
at jdk.internal.reflect.GeneratedMethodAccessor153.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrap.invoke(PogoMetaMethodSite.java:182)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:73)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
at io.restassured.internal.path.json.JSONAssertion.eval(JSONAssertion.groovy:80)
at jdk.internal.reflect.GeneratedMethodAccessor152.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:193)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:61)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:203)
at io.restassured.internal.path.json.JSONAssertion.getAsJsonObject(JSONAssertion.groovy:46)
... 33 more
]]>
    </error>
  </testcase> <!-- mIKO_AUTH_041_RegisterTests -->
  <system-out/>
  <testcase classname="authentication.Register" name="mIKO_AUTH_036_RegisterTests" time="0.894">
    <failure message="The following asserts failed:
	Response showing different status code. expected [200] but found [422],
	Response showing different status message. expected [true] but found [false],
	Response showing different mobile no expected [+919555555555] but found [null],
	Response showing different message expected [Otp sent successfully] but found [null],
	Response showing different status code. expected [200] but found [422],
	Response showing different status message. expected [true] but found [false],
	Response showing different email address expected [user05@testing.com] but found [null],
	Response showing different message expected [Otp sent successfully] but found [null],
	Response showing different status code. expected [200] but found [422],
	Response showing different status message. expected [true] but found [false],
	Response showing different phone no . expected [+919555555555] but found [null],
	Response showing different email address expected [user05@testing.com] but found [null],
	Response showing different message expected [Otp sent successfully] but found [null],
	Response showing different status code. expected [200] but found [422],
	Response showing different status message. expected [true] but found [false],
	Response showing different phone no . expected [+919555555555] but found [null],
	Response showing different email address expected [user05@testing.com] but found [null],
	Response showing First name expected [Test] but found [null],
	Response showing different Last name expected [Ing] but found [null],
	Response showing different message expected [Otp sent successfully] but found [null],
	Response showing different message expected [email_phone_of_diff_user] but found [null],
	Response showing different message expected [email_phone_of_diff_user] but found [null]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Response showing different status code. expected [200] but found [422],
Response showing different status message. expected [true] but found [false],
Response showing different mobile no expected [+919555555555] but found [null],
Response showing different message expected [Otp sent successfully] but found [null],
Response showing different status code. expected [200] but found [422],
Response showing different status message. expected [true] but found [false],
Response showing different email address expected [user05@testing.com] but found [null],
Response showing different message expected [Otp sent successfully] but found [null],
Response showing different status code. expected [200] but found [422],
Response showing different status message. expected [true] but found [false],
Response showing different phone no . expected [+919555555555] but found [null],
Response showing different email address expected [user05@testing.com] but found [null],
Response showing different message expected [Otp sent successfully] but found [null],
Response showing different status code. expected [200] but found [422],
Response showing different status message. expected [true] but found [false],
Response showing different phone no . expected [+919555555555] but found [null],
Response showing different email address expected [user05@testing.com] but found [null],
Response showing First name expected [Test] but found [null],
Response showing different Last name expected [Ing] but found [null],
Response showing different message expected [Otp sent successfully] but found [null],
Response showing different message expected [email_phone_of_diff_user] but found [null],
Response showing different message expected [email_phone_of_diff_user] but found [null]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at authentication.Register.mIKO_AUTH_036_RegisterTests(Register.java:243)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- mIKO_AUTH_036_RegisterTests -->
  <system-out/>
  <testcase classname="authentication.Register" name="mIKO_AUTH_040_RegisterTests" time="0.888">
    <error message="Cannot invoke method getAt() on null object" type="java.lang.IllegalArgumentException">
      <![CDATA[java.lang.IllegalArgumentException: Cannot invoke method getAt() on null object
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:72)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:286)
at io.restassured.internal.path.json.JSONAssertion.getAsJsonObject(JSONAssertion.groovy:57)
at io.restassured.internal.path.json.JSONAssertion$getAsJsonObject.callCurrent(Unknown Source)
at io.restassured.internal.path.json.JSONAssertion.getResult(JSONAssertion.groovy:28)
at io.restassured.path.json.JsonPath.get(JsonPath.java:203)
at com.miko.genericUtils.RestAssuredUtil.getJsonData(RestAssuredUtil.java:20)
at authentication.Register.mIKO_AUTH_040_RegisterTests(Register.java:326)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.NullPointerException: Cannot invoke method getAt() on null object
at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:44)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:34)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
at Script1.run(Script1.groovy:1)
at groovy.lang.GroovyShell.evaluate(GroovyShell.java:431)
at groovy.lang.GroovyShell.evaluate(GroovyShell.java:465)
at groovy.lang.GroovyShell.evaluate(GroovyShell.java:440)
at jdk.internal.reflect.GeneratedMethodAccessor153.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrap.invoke(PogoMetaMethodSite.java:182)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:73)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
at io.restassured.internal.path.json.JSONAssertion.eval(JSONAssertion.groovy:80)
at jdk.internal.reflect.GeneratedMethodAccessor152.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:193)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:61)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:203)
at io.restassured.internal.path.json.JSONAssertion.getAsJsonObject(JSONAssertion.groovy:46)
... 33 more
]]>
    </error>
  </testcase> <!-- mIKO_AUTH_040_RegisterTests -->
  <system-out/>
  <testcase classname="authentication.Register" name="mIKO_AUTH_047_RegisterTests" time="0.823">
    <failure message="The following asserts failed:
	Response showing different status code. expected [200] but found [422],
	Response showing different status message. expected [true] but found [false],
	Response showing different mobile no expected [+919555555555] but found [null],
	Response showing different message expected [Otp sent successfully] but found [null],
	Response showing different status code. expected [200] but found [422],
	Response showing different status message. expected [true] but found [false],
	Response showing different email address expected [user05@testing.com] but found [null],
	Response showing different message expected [Otp sent successfully] but found [null],
	Response showing different status code. expected [200] but found [422],
	Response showing different status message. expected [true] but found [false],
	Response showing different phone no . expected [+919555555555] but found [null],
	Response showing different email address expected [user05@testing.com] but found [null],
	Response showing different message expected [Otp sent successfully] but found [null],
	Response showing different status code. expected [200] but found [422],
	Response showing different status message. expected [true] but found [false],
	Response showing different phone no . expected [+919555555555] but found [null],
	Response showing different email address expected [user05@testing.com] but found [null],
	Response showing First name expected [Test] but found [null],
	Response showing different Last name expected [Ing] but found [null],
	Response showing different message expected [Otp sent successfully] but found [null],
	Response showing different message expected [email_phone_of_diff_user] but found [null],
	Response showing different message expected [email_phone_of_diff_user] but found [null],
	Response showing different status code. expected [200] but found [422],
	Response showing different status message. expected [true] but found [false],
	Response showing different error expected [Otp sent successfully] but found [null],
	Response showing different error expected [user789@testing.com] but found [null],
	Response showing different status code. expected [200] but found [422],
	Response showing different status message. expected [true] but found [false],
	Response showing different error expected [Otp sent successfully] but found [null],
	Response showing different error expected [user1$%^&amp;@testing.com] but found [null]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Response showing different status code. expected [200] but found [422],
Response showing different status message. expected [true] but found [false],
Response showing different mobile no expected [+919555555555] but found [null],
Response showing different message expected [Otp sent successfully] but found [null],
Response showing different status code. expected [200] but found [422],
Response showing different status message. expected [true] but found [false],
Response showing different email address expected [user05@testing.com] but found [null],
Response showing different message expected [Otp sent successfully] but found [null],
Response showing different status code. expected [200] but found [422],
Response showing different status message. expected [true] but found [false],
Response showing different phone no . expected [+919555555555] but found [null],
Response showing different email address expected [user05@testing.com] but found [null],
Response showing different message expected [Otp sent successfully] but found [null],
Response showing different status code. expected [200] but found [422],
Response showing different status message. expected [true] but found [false],
Response showing different phone no . expected [+919555555555] but found [null],
Response showing different email address expected [user05@testing.com] but found [null],
Response showing First name expected [Test] but found [null],
Response showing different Last name expected [Ing] but found [null],
Response showing different message expected [Otp sent successfully] but found [null],
Response showing different message expected [email_phone_of_diff_user] but found [null],
Response showing different message expected [email_phone_of_diff_user] but found [null],
Response showing different status code. expected [200] but found [422],
Response showing different status message. expected [true] but found [false],
Response showing different error expected [Otp sent successfully] but found [null],
Response showing different error expected [user789@testing.com] but found [null],
Response showing different status code. expected [200] but found [422],
Response showing different status message. expected [true] but found [false],
Response showing different error expected [Otp sent successfully] but found [null],
Response showing different error expected [user1$%^&@testing.com] but found [null]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at authentication.Register.mIKO_AUTH_047_RegisterTests(Register.java:478)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- mIKO_AUTH_047_RegisterTests -->
  <system-out/>
  <testcase classname="authentication.Register" name="mIKO_AUTH_046_RegisterTests" time="0.853">
    <failure message="The following asserts failed:
	Response showing different status code. expected [200] but found [422],
	Response showing different status message. expected [true] but found [false],
	Response showing different mobile no expected [+919555555555] but found [null],
	Response showing different message expected [Otp sent successfully] but found [null],
	Response showing different status code. expected [200] but found [422],
	Response showing different status message. expected [true] but found [false],
	Response showing different email address expected [user05@testing.com] but found [null],
	Response showing different message expected [Otp sent successfully] but found [null],
	Response showing different status code. expected [200] but found [422],
	Response showing different status message. expected [true] but found [false],
	Response showing different phone no . expected [+919555555555] but found [null],
	Response showing different email address expected [user05@testing.com] but found [null],
	Response showing different message expected [Otp sent successfully] but found [null],
	Response showing different status code. expected [200] but found [422],
	Response showing different status message. expected [true] but found [false],
	Response showing different phone no . expected [+919555555555] but found [null],
	Response showing different email address expected [user05@testing.com] but found [null],
	Response showing First name expected [Test] but found [null],
	Response showing different Last name expected [Ing] but found [null],
	Response showing different message expected [Otp sent successfully] but found [null],
	Response showing different message expected [email_phone_of_diff_user] but found [null],
	Response showing different message expected [email_phone_of_diff_user] but found [null],
	Response showing different status code. expected [200] but found [422],
	Response showing different status message. expected [true] but found [false],
	Response showing different error expected [Otp sent successfully] but found [null],
	Response showing different error expected [user789@testing.com] but found [null],
	Response showing different status code. expected [200] but found [422],
	Response showing different status message. expected [true] but found [false],
	Response showing different error expected [Otp sent successfully] but found [null],
	Response showing different error expected [user1$%^&amp;@testing.com] but found [null]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Response showing different status code. expected [200] but found [422],
Response showing different status message. expected [true] but found [false],
Response showing different mobile no expected [+919555555555] but found [null],
Response showing different message expected [Otp sent successfully] but found [null],
Response showing different status code. expected [200] but found [422],
Response showing different status message. expected [true] but found [false],
Response showing different email address expected [user05@testing.com] but found [null],
Response showing different message expected [Otp sent successfully] but found [null],
Response showing different status code. expected [200] but found [422],
Response showing different status message. expected [true] but found [false],
Response showing different phone no . expected [+919555555555] but found [null],
Response showing different email address expected [user05@testing.com] but found [null],
Response showing different message expected [Otp sent successfully] but found [null],
Response showing different status code. expected [200] but found [422],
Response showing different status message. expected [true] but found [false],
Response showing different phone no . expected [+919555555555] but found [null],
Response showing different email address expected [user05@testing.com] but found [null],
Response showing First name expected [Test] but found [null],
Response showing different Last name expected [Ing] but found [null],
Response showing different message expected [Otp sent successfully] but found [null],
Response showing different message expected [email_phone_of_diff_user] but found [null],
Response showing different message expected [email_phone_of_diff_user] but found [null],
Response showing different status code. expected [200] but found [422],
Response showing different status message. expected [true] but found [false],
Response showing different error expected [Otp sent successfully] but found [null],
Response showing different error expected [user789@testing.com] but found [null],
Response showing different status code. expected [200] but found [422],
Response showing different status message. expected [true] but found [false],
Response showing different error expected [Otp sent successfully] but found [null],
Response showing different error expected [user1$%^&@testing.com] but found [null]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at authentication.Register.mIKO_AUTH_046_RegisterTests(Register.java:457)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- mIKO_AUTH_046_RegisterTests -->
  <system-out/>
  <testcase classname="authentication.Register" name="mIKO_AUTH_044_RegisterTests" time="0.998">
    <failure message="The following asserts failed:
	Response showing different status code. expected [200] but found [422],
	Response showing different status message. expected [true] but found [false],
	Response showing different mobile no expected [+919555555555] but found [null],
	Response showing different message expected [Otp sent successfully] but found [null],
	Response showing different status code. expected [200] but found [422],
	Response showing different status message. expected [true] but found [false],
	Response showing different email address expected [user05@testing.com] but found [null],
	Response showing different message expected [Otp sent successfully] but found [null],
	Response showing different status code. expected [200] but found [422],
	Response showing different status message. expected [true] but found [false],
	Response showing different phone no . expected [+919555555555] but found [null],
	Response showing different email address expected [user05@testing.com] but found [null],
	Response showing different message expected [Otp sent successfully] but found [null],
	Response showing different status code. expected [200] but found [422],
	Response showing different status message. expected [true] but found [false],
	Response showing different phone no . expected [+919555555555] but found [null],
	Response showing different email address expected [user05@testing.com] but found [null],
	Response showing First name expected [Test] but found [null],
	Response showing different Last name expected [Ing] but found [null],
	Response showing different message expected [Otp sent successfully] but found [null],
	Response showing different message expected [email_phone_of_diff_user] but found [null],
	Response showing different message expected [email_phone_of_diff_user] but found [null]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Response showing different status code. expected [200] but found [422],
Response showing different status message. expected [true] but found [false],
Response showing different mobile no expected [+919555555555] but found [null],
Response showing different message expected [Otp sent successfully] but found [null],
Response showing different status code. expected [200] but found [422],
Response showing different status message. expected [true] but found [false],
Response showing different email address expected [user05@testing.com] but found [null],
Response showing different message expected [Otp sent successfully] but found [null],
Response showing different status code. expected [200] but found [422],
Response showing different status message. expected [true] but found [false],
Response showing different phone no . expected [+919555555555] but found [null],
Response showing different email address expected [user05@testing.com] but found [null],
Response showing different message expected [Otp sent successfully] but found [null],
Response showing different status code. expected [200] but found [422],
Response showing different status message. expected [true] but found [false],
Response showing different phone no . expected [+919555555555] but found [null],
Response showing different email address expected [user05@testing.com] but found [null],
Response showing First name expected [Test] but found [null],
Response showing different Last name expected [Ing] but found [null],
Response showing different message expected [Otp sent successfully] but found [null],
Response showing different message expected [email_phone_of_diff_user] but found [null],
Response showing different message expected [email_phone_of_diff_user] but found [null]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at authentication.Register.mIKO_AUTH_044_RegisterTests(Register.java:411)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- mIKO_AUTH_044_RegisterTests -->
  <system-out/>
  <testcase classname="authentication.Register" name="mIKO_AUTH_043_RegisterTests" time="0.966">
    <error message="Cannot invoke method getAt() on null object" type="java.lang.IllegalArgumentException">
      <![CDATA[java.lang.IllegalArgumentException: Cannot invoke method getAt() on null object
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:72)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:286)
at io.restassured.internal.path.json.JSONAssertion.getAsJsonObject(JSONAssertion.groovy:57)
at io.restassured.internal.path.json.JSONAssertion$getAsJsonObject.callCurrent(Unknown Source)
at io.restassured.internal.path.json.JSONAssertion.getResult(JSONAssertion.groovy:28)
at io.restassured.path.json.JsonPath.get(JsonPath.java:203)
at com.miko.genericUtils.RestAssuredUtil.getJsonData(RestAssuredUtil.java:20)
at authentication.Register.mIKO_AUTH_043_RegisterTests(Register.java:389)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.NullPointerException: Cannot invoke method getAt() on null object
at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:44)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:34)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
at Script1.run(Script1.groovy:1)
at groovy.lang.GroovyShell.evaluate(GroovyShell.java:431)
at groovy.lang.GroovyShell.evaluate(GroovyShell.java:465)
at groovy.lang.GroovyShell.evaluate(GroovyShell.java:440)
at jdk.internal.reflect.GeneratedMethodAccessor153.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrap.invoke(PogoMetaMethodSite.java:182)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:73)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
at io.restassured.internal.path.json.JSONAssertion.eval(JSONAssertion.groovy:80)
at jdk.internal.reflect.GeneratedMethodAccessor152.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:193)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:61)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:203)
at io.restassured.internal.path.json.JSONAssertion.getAsJsonObject(JSONAssertion.groovy:46)
... 33 more
]]>
    </error>
  </testcase> <!-- mIKO_AUTH_043_RegisterTests -->
  <system-out/>
  <testcase classname="authentication.Register" name="mIKO_AUTH_028_RegisterTests" time="0.838">
    <failure message="The following asserts failed:
	Response showing different status code. expected [200] but found [422],
	Response showing different status message. expected [true] but found [false],
	Response showing different mobile no expected [+919555555555] but found [null],
	Response showing different message expected [Otp sent successfully] but found [null]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Response showing different status code. expected [200] but found [422],
Response showing different status message. expected [true] but found [false],
Response showing different mobile no expected [+919555555555] but found [null],
Response showing different message expected [Otp sent successfully] but found [null]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at authentication.Register.mIKO_AUTH_028_RegisterTests(Register.java:52)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- mIKO_AUTH_028_RegisterTests -->
  <system-out/>
  <testcase classname="authentication.Register" name="mIKO_AUTH_037_RegisterTests" time="0.887">
    <failure message="The following asserts failed:
	Response showing different status code. expected [200] but found [422],
	Response showing different status message. expected [true] but found [false],
	Response showing different mobile no expected [+919555555555] but found [null],
	Response showing different message expected [Otp sent successfully] but found [null],
	Response showing different status code. expected [200] but found [422],
	Response showing different status message. expected [true] but found [false],
	Response showing different email address expected [user05@testing.com] but found [null],
	Response showing different message expected [Otp sent successfully] but found [null],
	Response showing different status code. expected [200] but found [422],
	Response showing different status message. expected [true] but found [false],
	Response showing different phone no . expected [+919555555555] but found [null],
	Response showing different email address expected [user05@testing.com] but found [null],
	Response showing different message expected [Otp sent successfully] but found [null],
	Response showing different status code. expected [200] but found [422],
	Response showing different status message. expected [true] but found [false],
	Response showing different phone no . expected [+919555555555] but found [null],
	Response showing different email address expected [user05@testing.com] but found [null],
	Response showing First name expected [Test] but found [null],
	Response showing different Last name expected [Ing] but found [null],
	Response showing different message expected [Otp sent successfully] but found [null],
	Response showing different message expected [email_phone_of_diff_user] but found [null],
	Response showing different message expected [email_phone_of_diff_user] but found [null]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Response showing different status code. expected [200] but found [422],
Response showing different status message. expected [true] but found [false],
Response showing different mobile no expected [+919555555555] but found [null],
Response showing different message expected [Otp sent successfully] but found [null],
Response showing different status code. expected [200] but found [422],
Response showing different status message. expected [true] but found [false],
Response showing different email address expected [user05@testing.com] but found [null],
Response showing different message expected [Otp sent successfully] but found [null],
Response showing different status code. expected [200] but found [422],
Response showing different status message. expected [true] but found [false],
Response showing different phone no . expected [+919555555555] but found [null],
Response showing different email address expected [user05@testing.com] but found [null],
Response showing different message expected [Otp sent successfully] but found [null],
Response showing different status code. expected [200] but found [422],
Response showing different status message. expected [true] but found [false],
Response showing different phone no . expected [+919555555555] but found [null],
Response showing different email address expected [user05@testing.com] but found [null],
Response showing First name expected [Test] but found [null],
Response showing different Last name expected [Ing] but found [null],
Response showing different message expected [Otp sent successfully] but found [null],
Response showing different message expected [email_phone_of_diff_user] but found [null],
Response showing different message expected [email_phone_of_diff_user] but found [null]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at authentication.Register.mIKO_AUTH_037_RegisterTests(Register.java:264)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- mIKO_AUTH_037_RegisterTests -->
  <system-out/>
  <testcase classname="authentication.Register" name="mIKO_AUTH_034_RegisterTests" time="0.932">
    <failure message="The following asserts failed:
	Response showing different status code. expected [200] but found [422],
	Response showing different status message. expected [true] but found [false],
	Response showing different mobile no expected [+919555555555] but found [null],
	Response showing different message expected [Otp sent successfully] but found [null],
	Response showing different status code. expected [200] but found [422],
	Response showing different status message. expected [true] but found [false],
	Response showing different email address expected [user05@testing.com] but found [null],
	Response showing different message expected [Otp sent successfully] but found [null],
	Response showing different status code. expected [200] but found [422],
	Response showing different status message. expected [true] but found [false],
	Response showing different phone no . expected [+919555555555] but found [null],
	Response showing different email address expected [user05@testing.com] but found [null],
	Response showing different message expected [Otp sent successfully] but found [null],
	Response showing different status code. expected [200] but found [422],
	Response showing different status message. expected [true] but found [false],
	Response showing different phone no . expected [+919555555555] but found [null],
	Response showing different email address expected [user05@testing.com] but found [null],
	Response showing First name expected [Test] but found [null],
	Response showing different Last name expected [Ing] but found [null],
	Response showing different message expected [Otp sent successfully] but found [null],
	Response showing different message expected [email_phone_of_diff_user] but found [null],
	Response showing different message expected [email_phone_of_diff_user] but found [null]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Response showing different status code. expected [200] but found [422],
Response showing different status message. expected [true] but found [false],
Response showing different mobile no expected [+919555555555] but found [null],
Response showing different message expected [Otp sent successfully] but found [null],
Response showing different status code. expected [200] but found [422],
Response showing different status message. expected [true] but found [false],
Response showing different email address expected [user05@testing.com] but found [null],
Response showing different message expected [Otp sent successfully] but found [null],
Response showing different status code. expected [200] but found [422],
Response showing different status message. expected [true] but found [false],
Response showing different phone no . expected [+919555555555] but found [null],
Response showing different email address expected [user05@testing.com] but found [null],
Response showing different message expected [Otp sent successfully] but found [null],
Response showing different status code. expected [200] but found [422],
Response showing different status message. expected [true] but found [false],
Response showing different phone no . expected [+919555555555] but found [null],
Response showing different email address expected [user05@testing.com] but found [null],
Response showing First name expected [Test] but found [null],
Response showing different Last name expected [Ing] but found [null],
Response showing different message expected [Otp sent successfully] but found [null],
Response showing different message expected [email_phone_of_diff_user] but found [null],
Response showing different message expected [email_phone_of_diff_user] but found [null]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at authentication.Register.mIKO_AUTH_034_RegisterTests(Register.java:203)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- mIKO_AUTH_034_RegisterTests -->
  <system-out/>
</testsuite> <!-- authentication.Register -->
